name: PR build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: install, test, build
        run: |
          npm i
          npm run build
