name: PR build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: install
        run: npm i
      - name: test
        run: npm run test
      - name: build
        run: npm run build
