name: PR build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install, test, build
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
        run: npm i && npm run build
