name: Release
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install, test, build, publish
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
        run: npm i && npm run build:publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
