name: Release
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: install
        run: npm i
      - name: build
        run: npm run build --workspaces
      - name: test
        run: npm run test --workspaces
      - name: publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          npm publish --workspace=@deepsignal/core
          npm publish --workspace=@deepsignal/preact
          npm publish --workspace=@deepsignal/react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
