name: Release
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Test, build, publish
        run: npm run build:publish